version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: phongvanngo/nova-file-service
    container_name: nova-file-service
    environment:
      - DOMAIN=http://localhost:5500
      - PORT=3000
    ports:
      - "5500:3000"
    volumes:
      - ./storage:/uploads
